language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head

env:
  - "ACTIVEMODEL_VERSION=3.2.19"
  - "ACTIVEMODEL_VERSION=4.0.10"
  - "ACTIVEMODEL_VERSION=4.1.6"

matrix:
  exclude:
    - rvm: jruby-18mode
      env: "ACTIVEMODEL_VERSION=4.0.10"
    - rvm: jruby-18mode
      env: "ACTIVEMODEL_VERSION=4.1.6"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
